default:
  image: rust:latest
  before_script:
    - apt-get update
    - apt-get -y upgrade

variables:
  DOCKER_DRIVER: overlay2
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: node
  CI_REGISTRY_GROUP: masq.ai
  SAST_GOSEC_LEVEL: 3

cache:
  key: $CI_COMMIT_SHORT_SHA-$ARCH
  paths:
    - node
    - masq
    - dns_utility
    - port_exposer

stages:
  - build
  - sync
  - docker
  - security

.test:
  script:
    - ./multinode_integration_tests/ci/all.sh
  allow_failure: true

include:
  - project: masq.ai/shared-ci
    ref: develop
    file: pipelines/rust/build.yml
  - project: masq.ai/shared-ci
    ref: develop
    file: pipelines/cross-compile/aarch64-darwin.yml
  - project: masq.ai/shared-ci
    ref: develop
    file: pipelines/docker/cloud.yml
  - template: SAST.gitlab-ci.yml

sast:
  stage: security
  artifacts:
    paths: 
      - gl-sast-report.json
    reports:
      sast: [gl-sast-report.json]
